name: client
version: 1.0.0

publish_to: none

environment:
  sdk: ^3.0.5

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  http:
    git:
      url: https://github.com/SamJakob/dart-http.git
      ref: feat/cancellation
      path: pkgs/http

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
